### ISSUE TITLE
Jar merging failed: class_16X.class

### ISSUE THREAD

**Issue by Galaxtone** [Chocohead/Merger#1]
I am merging `b1.7.3` client and server jars.

![image](https://user-images.githubusercontent.com/22679778/72666055-88447e80-39dc-11ea-9808-f1d09f35e6da.png)
`Jar merging failed due to java.lang.RuntimeException: Exception merging class_166.class`

![image](https://user-images.githubusercontent.com/22679778/72666062-91355000-39dc-11ea-8b84-befb64fc2efc.png)
`Caused by: java.lang.IllegalStateException: Deadlocked over [<init>(I)V, method_980(I)Lclass_166;, method_982(I)Lclass_166;, method_974(II)Lclass_166;, method_176(I)I, method_1323(Lclass_224;)I, method_181(Lclass_224;Lclass_172;Lclass_129;IIII)Z, method_103(Lclass_224;Lclass_506;)F, method_68(Lclass_224;Lclass_129;Lclass_172;)Lclass_224;, method_981()I, method_95(I)I, method_984()Z, method_979(Z)Lclass_166;, method_986()I, method_985(I)Lclass_166;, method_987()Z, method_262(Lclass_224;Lclass_283;Lclass_283;)Z, method_102(Lclass_224;IIIILclass_283;)Z, method_263(Lclass_449;)I, method_36(Lclass_506;)Z, method_977(Lclass_224;Lclass_283;)V, method_988()Lclass_166;, method_492()Z, method_199()Z, method_978(Ljava/lang/String;)Lclass_166;, method_180()Ljava/lang/String;, method_177(Lclass_224;)Ljava/lang/String;, method_975(Lclass_166;)Lclass_166;, method_989()Lclass_166;, method_990()Z, method_991()Ljava/lang/String;, method_1324(I)I, method_976(Lclass_224;Lclass_129;Lclass_449;IZ)V, method_983(Lclass_224;Lclass_129;Lclass_172;)V, <clinit>()V] and [<init>(I)V, method_980(I)Lclass_166;, method_982(I)Lclass_166;, method_974(II)Lclass_166;, method_181(Lclass_224;Lclass_172;Lclass_129;IIII)Z, method_103(Lclass_224;Lclass_506;)F, method_68(Lclass_224;Lclass_129;Lclass_172;)Lclass_224;, method_981()I, method_95(I)I, method_984()Z, method_979(Z)Lclass_166;, method_986()I, method_985(I)Lclass_166;, method_987()Z, method_262(Lclass_224;Lclass_283;Lclass_283;)Z, method_102(Lclass_224;IIIILclass_283;)Z, method_263(Lclass_449;)I, method_36(Lclass_506;)Z, method_977(Lclass_224;Lclass_283;)V, method_988()Lclass_166;, method_978(Ljava/lang/String;)Lclass_166;, method_180()Ljava/lang/String;, method_975(Lclass_166;)Lclass_166;, method_989()Lclass_166;, method_990()Z, method_991()Ljava/lang/String;, method_976(Lclass_224;Lclass_129;Lclass_449;IZ)V, method_983(Lclass_224;Lclass_129;Lclass_172;)V, method_199()Z, <clinit>()V]
        at net.fabricmc.stitch.merge.ClassMerger.mergePreserveOrder(ClassMerger.java:274)
        at net.fabricmc.stitch.merge.ClassMerger$Merger.<init>(ClassMerger.java:55)
        at net.fabricmc.stitch.merge.ClassMerger$3.<init>(ClassMerger.java:229)
        at net.fabricmc.stitch.merge.ClassMerger.merge(ClassMerger.java:229)
        at net.fabricmc.stitch.merge.JarMerger.lambda$2(JarMerger.java:290)
        ... 13 more`

**Comment by Chocohead** [comment]
The cycle has formed around `method_199()Z`, the server has it matched as the final method in the class whilst the client has subsequent methods after it which the server has before. Therefore they are not the same method (given Mojang doesn't rearrange them in any way, only strip) so shouldn't be matched between the jars.

For what it's worth if it is only Beta 1.7.3 you want I've already done it (complete with Stitch Intermediaries) [here](https://gist.githubusercontent.com/Chocohead/b7ea04058776495a93ed2d13f34d697a/raw/002292ee67bb1b66171bf97c4a3c9d3c4ae9e5f3/Beta%25201.7.3%2520Merge.tiny). Valo and co have also been giving them (cursed) names [here](https://github.com/minecraft-cursed-legacy/Minecraft-Cursed-POMF), which gives an idea how Yarn needs setting up.

**Comment by Galaxtone** [comment]
I'm not quite sure how to fin the location of `method_199()Z`

**Comment by Chocohead** [comment]
Given you're merging `class_166` which extends `Object`, it'll be in `ej` on the server and `gm` on the client. The mapping file always exports first so any generated names can be found in that if you're having problems. I think they attach anyway even if exporting the jar fails so Matcher might well have the method names in the class too.

**Comment by Galaxtone** [comment]
It worked, thank you.
